version: "3.3"

services:
  pg_tasks:
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      - POSTGES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - dockercompose
  backend:
    depends_on:
      - postgres
    image: flaskapp
    ports:
      - "5000:5000"
    volumes:
      - ./app:/usr/src/app/app
      - ./migrations:/usr/src/app/migrations
    restart: always
    
    networks:
      - dockercompose

networks:
  dockercompose: